name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    needs: [trufflehog_scan, semgrep_scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build a Docker image
        run: docker build -t / .

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: /
          args: --file=Dockerfile --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk.sarif
          path: snyk.sarif

  trufflehog_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: TruffleHog Action
        uses: trufflesecurity/trufflehog@v3.0.1
        with:
          scanArguments: "--format sarif --output trufflehog-report.sarif"

      - name: Upload SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-sarif-report
          path: trufflehog-report.sarif

  semgrep_scan:
    runs-on: ubuntu-latest
    needs: trufflehog_scan
    steps:
      - name: Run Semgrep
        run: |
          docker run --rm -v ${{ github.workspace }}:/src returntocorp/semgrep semgrep \
            --config="p/r2c-ci" \
            --sarif --output /src/semgrep.sarif /src

      - name: Upload Semgrep SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sarif-report
          path: semgrep.sarif