# This updated YAML file will:

# Check out the repository.
# Install Docker on the runner.
# Build the Docker image for NodeGoat.
# Start a Docker container with the built image.
# Test the deployment by displaying the username and listing the running Docker containers.

name: Build, deploy, and scan NodeGoat on WMD Docker servers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy_and_scan:
    name: Deploy and Scan on WMD server
    runs-on: itas276-SamjotSingh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: |
          docker build -t nodegoat-image .

      - name: Start Docker Container
        run: |
          docker run -d -p 40403:4000 --name nodegoat-container nodegoat-image

      - name: Test Deployment
        run: |
          whoami
          docker ps

      - name: Install Semgrep
        run: |
          echo "Installing Semgrep..."
          curl -L https://semgrep.dev/install.sh | bash

      - name: Run Semgrep SAST Scan
        run: |
          echo "Running Semgrep SAST Scan..."
          semgrep --sarif sast-report.sarif .

      - name: Save Semgrep SARIF Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sarif-report
          path: sast-report.sarif

      - name: Install Snyk
        run: |
          echo "Installing Snyk..."
          npm install -g snyk

      - name: Run Snyk SCA Scan
        run: |
          echo "Running Snyk SCA Scan..."
          snyk test --all-projects --sarif -o snyk-report.sarif

      - name: Save Snyk SARIF Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-sarif-report
          path: snyk-report.sarif
