name: Build and deploy NodeGoat to WMD Docker servers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: "Deploy to ITAS WMD server"
    runs-on: itas276-SamjotSingh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: |
          docker build -t nodegoat-image .

      - name: Start Docker Container
        run: |
          docker run -d -p 40304:4000 --name nodegoat-container nodegoat-image

      - name: Test Deployment
        run: |
          whoami
          docker ps
