name: Build, deploy, and scan NodeGoat on WMD Docker servers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  SAST-Semgrep:
    name: SAST Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:   
      - name: Notify start of SAST Semgrep Scan
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: "Starting SAST Semgrep Scan"
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Semgrep SAST scan
        run: |
          semgrep \
          --sarif --output semgrep-sast-report.sarif \
          --config="p/default" \
          --exclude="node_modules/*"
      - name: Save Semgrep SAST report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sast-report
          path: semgrep-sast-report.sarif
      - name: Notify completion of SAST Semgrep Scan
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: "Completed SAST Semgrep Scan"

  SCA-Snyk:
    name: SCA Scan with Snyk
    runs-on: ubuntu-latest
    container:
      image: snyk/snyk-cli:docker
    steps:
      - name: Notify start of SCA Scan with Snyk
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: "Starting SCA Scan with Snyk"
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Snyk
        run: snyk auth "3280d6a3-2a71-4aba-8f44-9c6debcec093"

      - name: Run Snyk SCA scan
        run: |
          snyk test --all-projects --json > snyk-sca-report.json || true
      - name: Convert Snyk SCA JSON report to SARIF
        run: |
          npm install -g snyk-to-sarif
          snyk-to-sarif --input snyk-sca-report.json --output snyk-sca-report.sarif
      - name: Save Snyk SCA report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca-report
          path: snyk-sca-report.sarif
      - name: Notify completion of SCA Scan with Snyk
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: "Completed SCA Scan with Snyk"

  TruffleHog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    needs: [SAST-Semgrep, SCA-Snyk]
    steps:
      - name: Notify start of TruffleHog Scan
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: "Starting TruffleHog Scan"
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog Scan
        run: trufflehog .
        continue-on-error: true
        # This continues the workflow even if trufflehog fails

      - name: Save TruffleHog report as pipeline artifact
        run: trufflehog . > trufflehog-report.txt
        continue-on-error: true
        # This continues the workflow even if trufflehog fails

      - name: Save TruffleHog report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog-report.txt
      - name: Notify completion of TruffleHog Scan
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: "Completed TruffleHog Scan"

  SARIF-Viewer:
    name: SARIF Report Viewer
    runs-on: ubuntu-latest
    needs: [SAST-Semgrep, SCA-Snyk, TruffleHog]
    steps:
      - name: Download Semgrep SAST report
        uses: actions/download-artifact@v2
        with:
          name: semgrep-sast-report
          path: sarif-report
      - name: Copy SARIF file
        run: cp sarif-report/semgrep-sast-report.sarif .
      - name: Save SARIF report as pipeline artifact
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-sarif-report
          path: semgrep-sast-report.sarif
      - name: Notify completion of SARIF Report Viewer
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN}}
          content: "Completed SARIF Report Viewer"

  E2E-Test-Discord:
    name: E2E Test and Discord Notification
    runs-on: ubuntu-latest
    needs: [SARIF-Viewer]
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "E2E Test Job is starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.actor }}"
      - name: Run E2E Test
      # Add your E2E test steps here
      - name: Discord Notification for completion of E2E Test
        uses: discord/action@v2
        with:
          webhook-id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook-token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: |
            E2E Test completed. Here is the SARIF report: [Download SARIF Report](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/semgrep-sarif-report/semgrep-sast-report.sarif) You can view the full workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
    
 
