name: Build, deploy, and scan NodeGoat on WMD Docker servers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Discord-Begin:
    name: Post a message to #itas-276-github-alerts when your workflow starts
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          content: "Security Pipeline jobs are starting..."

  E2E-Test-Discord:
    name: Post a message to #itas-276-github-alerts for E2E Test stage
    runs-on: ubuntu-latest
    needs: [Discord-Begin]
    steps:
      - name: Discord Notification for completion of E2E Test
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            E2E Test completed. Here is the SARIF report: [Download SARIF Report](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/semgrep-sarif-report/semgrep-sast-report.sarif)
            Full workflow run: [View workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

  SAST-Semgrep:
    name: Post a message to #itas-276-github-alerts for SAST Semgrep Scan stage
    runs-on: ubuntu-latest
    needs: [E2E-Test-Discord]
    steps:   
      - name: Notify start of SAST Semgrep Scan
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Starting SAST Semgrep Scan"
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Semgrep SAST scan
        run: |
          semgrep \
          --sarif --output semgrep-sast-report.sarif \
          --config="p/default" \
          --exclude="node_modules/*"
      - name: Save Semgrep SAST report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sast-report
          path: semgrep-sast-report.sarif
      - name: Notify completion of SAST Semgrep Scan
        uses: discordjs/discord.js
        with:
          type: text
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Completed SAST Semgrep Scan"

  SCA-Snyk:
    name: Post a message to #itas-276-github-alerts for SCA Scan with Snyk stage
    runs-on: ubuntu-latest
    needs: [SAST-Semgrep]
    steps:
      - name: Notify start of SCA Scan with Snyk
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Starting SCA Scan with Snyk"
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Snyk
        run: snyk auth "3280d6a3-2a71-4aba-8f44-9c6debcec093"

      - name: Run Snyk SCA scan
        run: |
          snyk test --all-projects --json > snyk-sca-report.json || true
      - name: Convert Snyk SCA JSON report to SARIF
        run: |
          npm install -g snyk-to-sarif
          snyk-to-sarif --input snyk-sca-report.json --output snyk-sca-report.sarif
      - name: Save Snyk SCA report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca-report
          path: snyk-sca-report.sarif
      - name: Notify completion of SCA Scan with Snyk
        uses: discordjs/discord.js
        with:
          type: text
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Completed SCA Scan with Snyk"

  TruffleHog:
    name: Post a message to #itas-276-github-alerts for TruffleHog Scan stage
    runs-on: ubuntu-latest
    needs: [SCA-Snyk]
    steps:
      - name: Notify start of TruffleHog Scan
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Starting TruffleHog Scan"
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog Scan
        run: trufflehog .
        continue-on-error: true
        # This continues the workflow even if trufflehog fails

      - name: Save TruffleHog report as pipeline artifact
        run: trufflehog . > trufflehog-report.txt
        continue-on-error: true
        # This continues the workflow even if trufflehog fails

      - name: Save TruffleHog report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog-report.txt
      - name: Notify completion of TruffleHog Scan
        uses: discordjs/discord.js
        with:
          type: text
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Completed TruffleHog Scan"

  SARIF-Viewer:
    name: Post a message to #itas-276-github-alerts for SARIF Report Viewer stage
    runs-on: ubuntu-latest
    needs: [TruffleHog]
    steps:
      - name: Notify start of SARIF Report Viewer
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Starting SARIF Report Viewer"
